name: linter and tester

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    container: python:3.10-alpine
    # services:
    #   azurite:
    #     image: mcr.microsoft.com/azure-storage/azurite 
    steps:
      - name: Sample linter
        run: echo "running linter"
  test:
    runs-on: ubunutu-latest
    steps:
      - name: Sample test
        run: echo "running test"