name: initiate and test
on: 
  push:
    branches:
      - 'main'
jobs:
  linter:
    runs-on: ubuntu-latest
    container: 
      image: python:3.10-slim-buster
    env:
      STORAGE_CONN_STRING = 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1;'
    services:
      azurite: 
        image: mcr.microsoft.com/azure-storage/azurite
      elasticsearch:
        image: elasticsearch:8.15.0
        env:
          discovery.type=single-node
          xpack.security.enabled=false 
          xpack.security.http.ssl.enabled=false
    steps:
      - name: get code
        uses: actions/checkout@v4
      # - name: set up python 3.10
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: '3.10'
      - name: install required modules
        run: pip install -r requirements.txt
      - name: initiate services
        run: python initiate_services.py
      - name: run test
        run: pytest -vxs