name: initiate and test
on: 
  push:
    branches:
      - 'main'
jobs:
  linter:
    runs-on: ubuntu-latest
    container: 
      image: python:3.10-slim-buster
    services:
      azurite: 
        image: mcr.microsoft.com/azure-storage/azurite
      elasticsearch:
        image: elasticsearch:8.15.0
        options: >-
          -e "discovery.type=single-node"
          -e "xpack.security.enabled=false" 
          -e "xpack.security.http.ssl.enabled=false"
    steps:
      - name: get code
        uses: actions/checkout@v4
      # - name: set up python 3.10
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: '3.10'
      - name: install required modules
        run: pip install -r requirements.txt
      - name: initiate services
        run: python initiate_services.py
      - name: run test
        run: pytest -vxs